import Head from 'next/head'
import Link from 'next/link'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main>
      {/* <Navbar /> */}
      <h1>Homepage</h1>
      <p >Hello! We are going to create a new Next js App</p>
      <Link href="/testing">
        <a className={styles.btn}> Show testing page </a>
        </Link>
      {/* <Footer /> */}
    </main>
    </div>
  )
}
